modLoader="javafml"
license="MIT License"
loaderVersion="[49,)"
issueTrackerURL=""
logoFile="logo.png"

[[mods]]
modId="mimi"
displayName="MIMI"
version="${file.jarVersion}"
authors="tofodroid"
description='''
MIMI - Musical Instrument Minecraft Interface
'''

[[dependencies.mimi]]
    modId="forge"
    mandatory=true
    versionRange="[49,)"
[[dependencies.mimi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.4, 1.21.0)"
    side="BOTH"