modLoader="javafml"
license="MIT License"
loaderVersion="[39,)"
issueTrackerURL=""
logoFile="logo.png"

[[mods]]
modId="mimi"
displayName="MIMI"
version="${file.jarVersion}"
authors="tofodroid"
description='''
MIMI - Musical Instrument Minecraft Interface
'''

[[dependencies.mimi]]
    modId="forge"
    mandatory=true
    versionRange="[44.1.0,)"
[[dependencies.mimi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20.0)"
    side="BOTH"